# Site settings
title:          Kaustav
description:    "I am Kaustav Ghosh, a Software Engineer from India. Currently, I'm working at Microsoft in Tallinn. I am passionate about real-time video communication, Android Open Source Project, and Linux. Over the past few years, I have also worked on web and mobile application development."
url:            "http://kaustav.co"

# Author
author:
  name:         Kaustav Ghosh
  url:          http://kaustav.co
  email:        kaustav.ghosh28@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
