# Site settings
title:          Kaustav
description:    "Kaustav's space"
url:            "http://kaustav.co"

# Author
author:
  name:         Kaustav Ghosh
  url:          http://kaustav.co
  email:        kaustav.ghosh28@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
